elastic/apm-queue

- .github/workflows/ci.yml
- kafka/doc.go
- pubsublite/consumer.go
- pubsublite/doc.go
- pubsublite/producer.go
- tools/tools.go
Adds the event processor in the PubSub message headers, which will allow subscribers to filter on certain events types. Also adds missing headers in a few files. See https://cloud.google.com/pubsub/docs/subscription-message-filter.
> Add processor type to pubsub.Message attributes

- kafka/consumer.go
- pubsublite/consumer.go
- pubsublite/producer.go
- queuecontext/context.go
Removes the project context enrichment / extraction and instead uses a more versatile and abstract map[string]string to store arbitrary k/v in the context.
> context: Enrich / extract metadata (string map)

- pubsublite/consumer.go
- pubsublite/consumer_test.go
- queue.go
Introduce a `Delivery` configuration option for the pubsublite consumer, allowing the caller to configure the message acknowledgement strategy.
The two supported strategies are: `AtMostOnce` and `AtLeastOnce`. The former is the current default (if left unspecfied), while the latter is not exactly at least once (depending on the implementation of the batch processor).
The configuration options have been documented to avoid confusion.
> pubsublite(consumer): default AtMostOnce delivery

- kafka/producer.go
Breaking change for kafka producer to accept brokers instead of just one broker.
> Use slice of broker addresses in kafka producer

- kafka/consumer.go
- kafka/producer.go
Updates the `Health` method for the Kafka producer and consumer to use the `client.Ping()` which forces the client to reach out to a Broker.
> kafka: update `Health()` to use `client.Ping()`

- kafka/consumer.go
Updates the Kafka consumer to consume from partitions via dedicated go- routines. Each assigned partition for the consumer in the consumer group will be consumed concurrently.
A `consumer` and `partitionConsumer` types are introduced, the former manages the assigned and revoked / lost partitions, and ensure that the latter (`partitionConsumer`) is created on assignment of new partitions, and stopped on revoked / lost partitions.
Closes #23
> consumer(kafka): Concurrently consume partitions

- infra/k8s/kafka/.helmignore
- infra/k8s/kafka/Chart.yaml
- infra/k8s/kafka/templates/kafka-single.yaml
- infra/k8s/kafka/templates/topic.yaml
- infra/k8s/kafka/values.yaml
- infra/module/pubsublite/main.tf
- queue.Tiltfile
Adds a new Kafka Helm chart, which creates a new Kafka ephemeral cluster with an optional number of Kafka topics, and a pubsublite Terraform module to provision an arbitrary number of pubsublite topics, optionally creating subscriptions for each of those.
Last, `queue.Tiltfile` is meant to be loaded by a Tiltfile to provision the desired "queue" type.
Part of #42
> Tilt: Add kafka Helm chart, pubsublite tf module

- queue.Tiltfile
Update the `queue.Tiltfile` to always run `terraform init` before apply.
> tilt: Always run `terraform init`

- kafka/producer.go
Introduce a new `kafka.CompressionCodec` type alias as to not directly tie clients to the underlying implementation library.
Also adds a constructor function for each of the supported codecs.
> kafka(producer): Add CompressionCodec type alias

- .github/workflows/opentelemetry.yml
This will help to visualise the GitHub workflow runs as APM traces
It requires a couple of secrets to be added, though I'm not admin, so I can send you over them 
Cheers
> action: export GH workflow runs to APM data

- kafka/producer.go
- kafka/producer_test.go
- queuecontext/context.go
- queuecontext/context_test.go
Fixes the async producing by detaching the `context.Context.Deadline` from the passed context in ProcessBatch, but maintaining context.Values that may be defined, which allows trace context to be propagated down to the kgo client.
Closes #53
> kafka(producer): Fix async producing

- .github/renovate.json
Ignores the `github.com/elastic/apm-queue` module, since it's used by `cmd/loadgen` and that dependency is replaced by the contents of the local module.
Additionally, updates the renovate config to match the Elastic policy.
> renovate: Update policy, ignore `apm-queue`

- kafka/producer.go
Fixes the `span.End()` for Async producing. Also, captures any errors in the span if they are reported. Last, removes the RecordMutators that were introduced before TopicRouter.
> kafka(producer): Fix OTel `span.End()`

- kafka/producer_test.go
franz-go runs the hooks to finish events in an unchecked goroutine:
https://github.com/twmb/franz-go/blob/master/pkg/kgo/producer.go#L436-L440
This method calls `finishPromises`, which calls `OnProduceRecordUnbuffered`, which is the hook that kotel uses to end the span.
Because of that, the check on the number of created spans is flaky: https://github.com/elastic/apm-queue/actions/runs/4763014463/jobs/8466352708
We don't have any way to know whether kgo has finished running the goroutine. So by sleeping for a millisecond, we reduce the risk of the flaky issue happening.
If kgo took more than 1ms to process the hooks, that seems like something which would be a performance issue to investigate anyway.
> Sleep in producer test to reduce the risk of flaky test

- systemtest/infra.go
Increase terraform installation timeout. Mostly relevant for people with a slow internet connection.
The default timeout is not enough and systemtests will fail with a generic error "context cancelled"
> systemtest: increase terraform installer timeout

- systemtest/infra_kafka.go
- systemtest/infra_pubsublite.go
- systemtest/main_test.go
While debugging https://github.com/elastic/apm-queue/pull/109 I received a generic error: "context cancelled". 
Wrapping errors should help to undestand where the error is coming from.
> systemtest: wrap provisioning errors for clarity

- Makefile
Closes https://github.com/elastic/apm-queue/issues/106
Run `go mod tidy` within the `lint` context so the CI will run it too.
> ci: add go mod tidy

- systemtest/infra_kafka.go
- systemtest/infra_pubsublite.go
Use `context.Background()` for the `tf.Destroy` call, since otherwise the destruction will be tied to the test context, which may be canceled by the time it is called. Also log any errors from `tf.Destroy`.
> systemtest: Use `ctx.Background` for `tf.Destroy`

- kafka/consumer.go
- kafka/consumer_test.go
- kafka/producer.go
- pubsublite/consumer.go
- pubsublite/producer.go
- queue.go
Pass context to healthcheck methods. Useful to make sure the request context is passed on. 
Closes https://github.com/elastic/apm-queue/issues/96
> feat: pass context to health checks

- pubsublite/consumer.go
Replace ConsumerConfig.Subscriptions with
Project, Region, and Topics. These are used
by the implementation to form a subscription.
This brings the kafka and pubsublite APIs in line.
> pubsublite: configure consumer with topics

- pubsublite/consumer.go
This is no longer required now that Subscription
is derived from topics and GCP region/project.
We can probably unexport Subscription, but I'll
leave that for another day.
> pubsublite: remove Subscription.Validate method

- kafka/producer.go
Flush events when closing the producer.
This leads to event loss which can be identified when testing lossless graceful shutdown with an async producer.
The logs will contain the following messages:
```
ERROR   failed producing message        {"error": "client closed", "topic": "topic", "offset": 0, "partition": 0, "headers": null}
```
As a solution, we make sure that any buffered events is flushed before closing the client.
> fix: flush events when closing the kafka producer

- pubsublite/producer.go
Another issue discovered while working on https://github.com/elastic/apm-queue/pull/116
This PR update the pubsub producer to not panic when closed multiple times. The behaviour is consistent with the kafka producer.
> fix: do not panic when trying to close the pubsub producer multiple time

- kafka/producer.go
- kafka/producer_test.go
- pubsublite/producer.go
- pubsublite/producer_test.go
Updates `kafka.Producer.Close()` to return any errors returned by the `kgo.Client.Flush()` call.
Updates `pubsublite.Producer.Close()` to delete producers that have been stopped.
Adds a `TestProducerConcurrentClose()` for both packages.
> producer: Add ConcurrentClose test, minor fixes

- pubsublite/consumer.go
Adds a bit more logging to the PubSub Lite consumer. This should make it easier to spot any processing errors and re-processing attempts.
Added while working on fixing #116
> pubsublite(consumer): Add minimal logging

- kafka/consumer.go
- kafka/consumer_test.go
#104 properly configured kotel for producers. But I forgot the consumers when setting that up.
This sets it up there too, so we do get consumer traces.
> Properly configure kotel for consumers

- systemtest/infra.go
Do not try to download and install terraform if available locally.
terraform and provider versions can be enforced in the terraform file.
Related to https://github.com/elastic/apm-queue/issues/149
> test: do not try to download and install terraform if available locally

- systemtest/produce_consume_basic_test.go
Add a systemtest to verify consistent behaviour on shutdown.
The test is creating a producer, sendin an event, creating a consumer and finally closing the consumer.
Consumer is closed in two ways:
- ctx is canceled
- consumer is closed
Related https://github.com/elastic/apm-queue/issues/147
> test: add systemtest to verify consistent behaviour on shutdown

- systemtest/produce_consume_delivery_test.go
This is the last remaining systemtest mentioned in the issues. 
Port the delivery type unit tests to systemtest.
Kafka tests are passing
pubsub tests are failing
Related to https://github.com/elastic/apm-queue/issues/122
Related to https://github.com/elastic/apm-queue/issues/124
> test: add delivery systemtests

- systemtest/produce_consume_shutdown_test.go
Add lossless graceful shutdown systemtests.
Mostly inspired by the current lossless graceful shutdown unit tests.
Related to https://github.com/elastic/apm-queue/issues/124
Related to https://github.com/elastic/apm-queue/issues/122
> test: add systemtests for lossless graceful shutdown

- kafka/common.go
- kafka/common_test.go
- kafka/consumer.go
- kafka/manager.go
- kafka/producer.go
If CommonConfig.Brokers is unspecified, look for $KAFKA_BROKERS and treat it as a comma-separated list of broker addresses.
If CommonConfig.SASL is unspecified, look for $KAFKA_USERNAME and $KAFKA_PASSWORD and treat them as SASL/PLAIN credentials.
> kafka: set defaults from environment

- kafka/consumer.go
- kafka/consumer_test.go
- pubsublite/consumer.go
- queue.go
Updates the `kafka.Consumer` to behave like the `pubsublite.Consumer`. This includes:
- Returning a `nil` error after the context is cancelled, or the client is closed.
- Returning an error if the consumer has already been started.
Closes #157 
Closes #147
> consumer(kafka): Fix close deadlock, update errors

- kafka/manager.go
- kafka/topiccreator.go
- kafka/topiccreator_test.go
This allows one to use a single Manager to create topics with differing partition counts and configs. It also enables one to create a Manager without specifying PartitionCount, e.g. in case one just wants to list topics.
> kafka: create separate TopicCreator type

- kafka/common.go
- kafka/manager.go
- kafka/manager_test.go
- kafka/topiccreator.go
Use kadm to measure consumer group lag, and report as OpenTelemetry metrics.
> kafka: measure consumer group lag

- kafka/consumer_test.go
- kafka/producer_test.go
Add a new partitions artgument to the `newClusterWithTopics` helper.
So #181 can specify 1 partition and remove test flakiness.
> kafka(test): Update kfake builder with partitions

- systemtest/infra_kafka.go
- systemtest/infra_pubsublite.go
- systemtest/logger.go
- systemtest/main_test.go
- systemtest/produce_consume_basic_test.go
- systemtest/producer_consumer.go
- systemtest/providers.go
Consolidates the loggers and creates a new logger that only prints the logs if the log has failed. This reduces the verbosity of the systemtest when run with the `-v` flag.
Also fixes the logger passed down to the created consumer/producer.
Closes #188
> systemtest: Only show logs on test failure

- .github/workflows/system-test.yml
- systemtest/infra.go
- systemtest/infra_kafka.go
- systemtest/infra_pubsublite.go
- systemtest/main_test.go
Ensure the Pub/Sub Lite reservation name's prefix
is scoped to the GitHub Actions job ID in CI, so
two unrelated PRs/jobs don't clobber each other's
infrastructure.
Update the Kafka namespace used in CI to remain
consistent for re-runs of a job, so we don't
accumulate namespaces.
Add a -destroy-only flag and call it in a CI step
that always runs, to ensure provisioned resources
are always destroyed at the end of a workflow.
Closes https://github.com/elastic/apm-queue/issues/169
> Clean up resources in CI properly

- kafka/manager.go
- pubsublite/common.go
- pubsublite/consumer.go
- pubsublite/consumer_test.go
- queue.go
- systemtest/infra.go
- systemtest/infra_pubsublite.go
- systemtest/providers.go
Remove the apmqueue.Subscription type. This type never really made sense for Kafka, since you configure the consumer group ID on the client and then consume multile topics by name. Instead, we derive the Pub/Sub Lite subscription name from a topic and consumer name (similar to consumer group ID).
> Remove apmqueue.Subscription

- pubsublite/common.go
- pubsublite/internal/pubsubabs/publisher.go
- pubsublite/internal/pubsubabs/publisher_test.go
- pubsublite/internal/telemetry/publisher.go
- pubsublite/internal/telemetry/publisher_test.go
- pubsublite/producer.go
This PR is the counterpart of #181 for the pubsublite package, with a bit of refactoring that was needed in order to be able test the metrics.
Introduces a new package `pubsubabs` which provides the necessary means to abstract the types in the `pubsub` package. Two new interfaces are introduced; `PublisherClient` implements the `pubsub.PublisherClient`, and `Publisher`, which returns a `PublishResult` interface that can be used to assert that our business logic works as expected in unit tests.
This allows us to start writing unit tests for the pubsublite.Publisher.
`telemetry.Producer` now implements the `pubsubabs.Publisher` interface and has been refactored from a function to a type.
`producer.messages.produced` and `produced.messages.errored` metrics are now recorded and reported using …
> pubsublite(publisher): Record metrics, add testing

- .github/workflows/system-test.yml
* Properly pass github token to workflow
* The GitHub token wasn't validated until last week.
> ci: correctly pass github token to workflow

- kafka/metrics.go
- kafka/metrics_test.go
Adds a new `consumer.messages.fetched` metric that records the number of fetched records from Kafka adding the record's headers as dimensions.
> kafka/consumer: Record `consumer.messages.fetched`

- kafka/metrics.go
- kafka/metrics_test.go
To uniform with PubSubLite producer and consumer, add [`MessagingSystem`](https://pkg.go.dev/go.opentelemetry.io/otel@v1.16.0/semconv/v1.17.0#MessagingSystem) attribute to Kafka metrics.
The same `MessagingSystem` attribute is applied to PubSubLite [publisher][1] and [consumer][2] metrics.
[1]: https://github.com/elastic/apm-queue/blob/41bf286b91f83f497cebb2489faa0e87449e0e38/pubsublite/internal/telemetry/publisher.go#L146
[2]: https://github.com/elastic/apm-queue/blob/41bf286b91f83f497cebb2489faa0e87449e0e38/pubsublite/internal/telemetry/consumer.go#L66
> Kafka metrics: add MessagingSystem attribute

- kafka/consumer_test.go
- kafka/metrics.go
- kafka/metrics_test.go
- kafka/producer.go
- kafka/producer_test.go
- pubsublite/internal/telemetry/consumer.go
- pubsublite/internal/telemetry/consumer_test.go
- pubsublite/producer.go
- queue.go
This adds a new header on each producer record, `timestamp`, which stores the time when the record was produced.
It also emits a new metric, `consumer.messages.delay`, which is the delay in milliseconds it took to consume a record.
> Add event delay metric on both producers

- .github/workflows/system-test.yml
In other discussions there was a concern, that there could be a short timeframe after the `is-pr-approved` action is done, where the`ref` could yield a new commit that is not actually verified.
This change should discard any ambiguity of which commit is checked out.
> Use sha instead of ref in system-tests

- go.mod
- kafka/consumer.go
- kafka/producer.go
- kafka/producer_test.go
- pubsublite/consumer.go
- pubsublite/producer.go
- queue.go
- systemtest/infra_kafka.go
- systemtest/infra_pubsublite.go
- systemtest/produce_consume_basic_test.go
- systemtest/providers.go
The ordering key allows Kafka and Pubsublite to ensure that a record with the same ordering key is routed to the same partition.
Franz-go library, by default, uses a [UniformBytesPartitioner](https://github.com/twmb/franz-go/blob/6147cee6468484e5dfab6febf4b76962dffaee38/pkg/kgo/config.go#L499) with ordering keys enabled and default murmur2 hasher. The `UniformBytesPartitioner` with ordering keys enabled uses the configured hash function to map a record with `Key` to a specific partition ([ref](https://github.com/twmb/franz-go/blob/6147cee6468484e5dfab6febf4b76962dffaee38/pkg/kgo/partitioner.go#L323-L325)). This means that we can keep using the default partitioner and satisfy the requirement for ordering keys.
> Introduce ordering key for kafka and pubsublite

- pubsublite/manager.go
- pubsublite/manager_test.go
Fix "AND and OR cannot be mixed for 'resource.labels' restrictions"
> pubsublite: monitoring: Filter by location on client side

- kafka/metrics.go
- kafka/metrics_test.go
Updates the consumer to use the Source rather than Destination attrs.
> kafka: Use `Source*` consumer metric attributes

- pubsublite/common.go
- pubsublite/consumer.go
- pubsublite/consumer_test.go
- pubsublite/manager.go
- pubsublite/manager_test.go
- pubsublite/producer.go
- pubsublite/producer_test.go
- pubsublite/topiccreator.go
- pubsublite/topiccreator_test.go
If CommonConfig.Namespace is non-empty, a prefix (filter) will be added to all namespaces, topics, and subscriptions.
The namespace will be stripped from returned names, and will be added as a separate attribute to metrics and logs.
Part of https://github.com/elastic/apm-queue/issues/224
> pubsublite: add resource namespacing

- kafka/common.go
- kafka/common_test.go
- kafka/consumer.go
- kafka/consumer_test.go
- kafka/manager.go
- kafka/manager_test.go
- kafka/metrics.go
- kafka/metrics_test.go
- kafka/producer.go
- kafka/producer_test.go
- kafka/topiccreator.go
- kafka/topiccreator_test.go
If `CommonConfig.Namespace` is non-empty, a prefix (filter) will be added to all topics. This enables the creation of a topic with the same logical name within two different namespaces. The namespace will be stripped from returned topic names, and will be added as a separate attribute to metrics and logs.
Closes https://github.com/elastic/apm-queue/issues/224
> kafka: add topic namespacing

- pubsublite/consumer_test.go
goroutine leak found while investigating data race in unit tests:
```
Goroutine 1408 in state select, with google.golang.org/grpc.(*addrConn).resetTransport on top of the stack:
goroutine 1408 [select]:
google.golang.org/grpc.(*addrConn).resetTransport(0xc000652600)
/go/pkg/mod/google.golang.org/grpc@v1.57.0/clientconn.go:1368 +0x3c9
google.golang.org/grpc.(*addrConn).connect(0xc000652600)
/go/pkg/mod/google.golang.org/grpc@v1.57.0/clientconn.go:993 +0x96
created by google.golang.org/grpc.(*acBalancerWrapper).Connect
/go/pkg/mod/google.golang.org/grpc@v1.57.0/balancer_conn_wrappers.go:398 +0x59
[originating from goroutine 79]:
google.golang.org/grpc.(*acBalancerWrapper).Connect(...)
/go/pkg/mod/google.golang.org/grpc@v1.57.0/balancer_conn_wrappers.go:399 +0x59 …
```
> test: fix pubsub consumer goroutine leak in TestConsumerConsume

- kafka/manager.go
- kafka/manager_test.go
We specify the consumer group name, so there's no need to also filter on the ProtocolType.
(@marclop noticed in some cases, possibly just with redpanda, that ProtocolType was empty.)
> kafka: remove ProtocolType filter in consumer lag

- cmd/queuebench/config.go
Number of partitions per topic is a relevant configuration to benchmark producing and consuming from Kafka queues.
This PR adds the `-partitions` flag that allows setting the partitions value instead of relying on the default (`1`).
> queuebench: add partitions flag

- kafka/consumer.go
Our kafka.ConsumerConfig has fields that relates directly to Kafka consumer
settings. This PR adds some more details about them and links to the
Kafka docs to help onboarding on what configuration options do.
> kafka/consumer: clarify wrapped Kafka settings

- kafka/common.go
- kafka/consumer_test.go
- kafka/producer_test.go
To reduce memory usage of applications that use this library, remove the usage of `kotel` tracing hooks to avoid creating a span for each event that is either read or written to Kafka.
Closes #300
> kafka: Remove record-level tracing

- kafka/topiccreator.go
- kafka/topiccreator_test.go
Updates the manager `CreateTopics` method to only issue the CreateTopics call if the topics don't exist in Kafka, preventing undesirable errors from being returned and logged.
> kafka: manager: List topics before creating them

- kafka/manager.go
- kafka/manager_test.go
- queue.go
Updates `kafka.Manager.MonitorConsumerLag` to allow monitoring unknown topics that match a regex expression.
> Kafka: Allow regex expression for topic monitoring

- kafka/manager.go
- kafka/manager_test.go
- kafka/topiccreator.go
- kafka/topiccreator_test.go
- metrictest/metric.go
Updates the `kafka` package to record the number of topics that have been created and deleted, improving the overall observability.
> kafka: Add topic creation & deletion metrics

- kafka/manager.go
- kafka/manager_test.go
- kafka/topiccreator.go
- kafka/topiccreator_test.go
Adds a new `topic` dimension to the `create`/`delete` metrics.
> kafka: Add `topic` to create/delete metrics

- kafka/consumer_bench_test.go
- kafka/producer_test.go
Adds consumer microbenchmarks with a variety of topic, partition, record count and MaxPollRecords.
> Kafka: Add consumer microbenchmarks

- kafka/consumer.go
Increases the default `MaxPollRecords` to `500`, which is inline with Kafka defaults.
> kafka: Increase default `MaxPollRecords` to `500`

- kafka/common.go
- kafka/consumer.go
- kafka/consumer_test.go
- kafka/manager.go
- kafka/metrics.go
Removes the need for dedicated goroutines to be spun when the consumer receives its partition assignments. Instead, it uses an `errgroup.Group` with a limit of `1`, which behaves like before.
This approach's primary advantage is that it reduces the number of running goroutines, which is noticeable as the partition count increases.
Without this patch, the consumer throughput plateaued after reaching a certain throughput.
> kafka: Remove partition consumer goroutines

- .github/actions/system-test/action.yml
- .github/workflows/system-test.yml
* Use OIDC to auth with Google services.
* Avoid the use of Vault and rely on keyless auth for CI.
> feat: use oidc for auth with GCP

- .github/workflows/system-test.yml
* Enable dependabot for system tests.
* It was disabled previously due to vault access.
* Since we are using OIDC, we can re-enable it.
> feat: enable dependabot for system tests

- .github/workflows/system-test.yml
Enable system-tests for push events in addition to Pull Requests in feature branches
I didn't see any executions for the system-tests on merge commits onto `main` in:
- https://github.com/elastic/apm-queue/actions/workflows/system-test.yml
But only for dependabot.
> github-action: support push events

- kafka/consumer.go
- kafka/consumer_test.go
- pubsublite/consumer.go
- pubsublite/consumer_test.go
- queue.go
- queuecontext/context.go
- queuecontext/context_test.go
We want to allow consumers to understand how many partitions they are poling from.
The partition Id is avaiable in both kafka and pubsublite so we should expose it and let consumers use it at their own advantage.
~We create a new un-exported string constant, with value `partition_id`. This will be populated in the context.Context attached to each kgo.Record via the `queuecontext` package.~
EDIT: accepted proposal to add the partition as a field of the `Record` struct.
Consumers will be ale to understand which partition a record was polled from by parsing the record field.
Unrelated small performance improvement: pre-allocate map capacity to the length of headers.
> feat: partition id as record metadata

- kafka/manager_test.go
- kafka/metrics.go
- kafka/metrics_test.go
This PR address https://github.com/twmb/franz-go/issues/670 but in the monitoring implementation introduced in this module by #460.
It changes Kafka connection metrics, instead of relying on 2 different metrics to report Kafka connections successes and failures, use only a single metric with distinct `outcome` attribute based on the outcome. This implementation does not guard this new behaviour under a flag, like I did for the contribution to `franz-go` as I don't think it's useful is a specialized implementation like we have here. But still this introduces a breaking change in the `kafka` package monitoring so I'm open to revisit this decision if we want to keep backwards compatibility.
Metric `messaging.kafka.connect_errors.count` has been removed.
Attribute `outcome` has been added to …
> Align connects metrics

- kafka/common.go
- kafka/consumer.go
- kafka/producer.go
This commit adds a few new configuration options to the kafka package.
* `MetadataMaxAge`: The maximum age of metadata before it is refreshed. The lower the value, the quicker the Kafka client will pick up topic changes.
* `ConsumePreferringLagFn`: A function that alters the order in which partitions are consumed by the consumer. Use with caution, as this can lead to uneven consumption of partitions.
* `RecordPartitioner`: A function that returns the partition to which a record should be sent.
> kafka: Add a few new config options

- kafka/common_test.go
- kafka/producer_test.go
This commit improves the stability of the consumer test by reducing the `FetchMaxWait` to 100ms.
> kafka: improve consumer test stability

- Makefile
Updates the `test` Makefile target to run the unit tests 10 times. This makes it harder to commit flaky tests by forcing multiple executions in the CI pipeline.
We could increase the number of times the tests are run, but 10 seems like a reasonable trade-off between stability and execution time.
> Improve unit test stability by running `10` times

- kafka/common.go
- kafka/logger.go
- kafka/logger_test.go
The current `metricsHook` struct that collects metrics based on Kafka hooks is not equipped to also report details of _why_ connection errors are caused.
We provide a new struct that implements a (single, for now) kgo Hook dedicated to logging errors during the broker connection phase.
The struct can be iterated in the future to implement other monitoring hooks, providing logging utilities where the metrics would have too high cardinality.
Currently, the proposed design adds the new logger hook behind the `CommonConfig.DisableTelemetry` flag (similarly to the metrics hook).
This can be improved and it is not a perfect solution, but it has to be done this way until a bigger refactor is done to expose the `CommonConfig.hook` fieldin some way.
The more idiomatic, but also more expensive, …
> Kafka: add hook to log connection error reasons

- kafka/metrics_test.go
Fixes https://github.com/elastic/apm-queue/issues/464
Adding a small delay after each record acknowledge seems to fix the flakiness of the `TestProducerMetrics/Producer` test.
The test only fails when running with `-race` locally:
```
go test -v -race -failfast ./kafka/
```
I am unable to properly deduce why this race is happening. From the solution it seems that the collector starts pulling metrics from the queue before a record has been ack. This makes no sense, since an ACK for ALL records are acknowledged before collection starts:
- `producer.Produce` successfully waits for all records to be ack on the queue
- `producer.Close` is actually blocking due to the `Flush` method being called: https://github.com/twmb/franz-go/blob/b77dd13e2bfaee7f5181df27b40ee4a4f6a73b09/pkg/kgo/producer.go#L …
> Fix flaky test in metric producer

- .github/workflows/add-to-project.yaml
No more finer-grained tokens but ephemeral tokens using a GH app
> github-actions: use ephemeral tokens for add to mis project

- .github/actions/system-test/action.yml
- .github/workflows/system-test.yml
This will replace the native `google-github-actions/auth` action with our opinionated `elastic/oblt-actions/google/auth` action.
The opinionated action comes with defaults, which are aligned with how we set up OIDC in a standardized way.
> ci: use elastic/oblt-actions/google/auth action

- kafka/logger.go
- kafka/logger_test.go
This change updates the logger to use WARN instead of ERROR for broker connect DeadlineExceeded errors. This is because DeadlineExceeded errors since they don't indicate a problem, but we still want to log them as warnings in case they correlate with other events.
> Use WARN for broker connect DeadlineExceeded errs

- kafka/common.go
- kafka/common_test.go
Adds support for Kafka to use client certificates based on two new env variables `KAFKA_TLS_CERT_PATH` and `KAFKA_TLS_KEY_PATH`. The current implementation supports hot reloading by checking if the file write time is greater than the last time it was read.
Most of the changes are in the form of unit tests.
> Kafka: Support specifying client certificates

- kafka/common.go
- kafka/common_test.go
In some cases, it is meaningful to set the [`tls.Config.ServerName`](https://cs.opensource.google/go/go/+/refs/tags/go1.24.0:src/crypto/tls/common.go;l=668) field (for example when brokers are replying to clients with their IP).
This PR adds configuration via environment variable to allow customizing the ServerName field.
> feat: allow customizing TLS ServerName
